[theme]

# Primary accent for interactive elements
primaryColor = '#f6620c'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "monospace"
